services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - type: bind
        source: ./postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: cryptoexchange

volumes:
  postgres-data:
